name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'content/**'
      - 'layouts/**'
      - 'static/**'
      - 'config.toml'
      - 'themes/**'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up Hugo
      - name: Setup Hugo
        uses: actions/setup-node@master
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run build

      # Step 3:Dploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/github-gh-pages@v3
        with:
          branch: gh-pages
          publish_dir: ./dist
          github_token: ${{ secrets.CICD_DEMO }}
          user_name: ${{ secrets.MY_USER_NAME }}
          user_email: ${{ secrets.MY_USER_NAME }}@users.noreply.github.com
          commit_message: 自动部署